#!/bin/bash
#$ -V
#$ -j y
#$ -N lorenz_ensemble
#$ -cwd
#$ -l cores=4
#$ -t 1:20

export OCL_PLATFORM=AMD

# warming run
./thrust_lorenz_ensemble_openmp 1024

rm -f thrust_cpu_${SGE_TASK_ID}.dat

for ((a=256;a<=67108864;a*=2)); do
    echo "$a"
    echo -n "$a " >> thrust_cpu_${SGE_TASK_ID}.dat
    /usr/bin/time -f %e -o thrust_cpu_${SGE_TASK_ID}.dat -a ./thrust_lorenz_ensemble_openmp $a > /dev/null
done
