#!/bin/bash
#$ -V
#$ -j y
#$ -N lorenz_ensemble
#$ -cwd
#$ -m ae -M ddemidov@ksu.ru
#$ -l cores=4,gpu=1

# Speed up cuda initialization on headless nodes.
nvidia-smi -l 2>&1 > /dev/null &
NVSMI_PID=$!

export OCL_PLATFORM=NVIDIA
export OCL_MAX_DEVICES=1

# warming runs
./thrust_lorenz_ensemble 1024
./vex_lorenz_ensemble 1024

rm -f thrust.dat
rm -f vexcl.dat

for ((a=256;a<=67108864;a*=2)); do
    echo "$a "
    for run in `seq 20`; do
	echo -n "."

	echo -n "$a " >> thrust.dat
	/usr/bin/time -f %e -o thrust.dat -a ./thrust_lorenz_ensemble $a > /dev/null

	echo -n "$a " >> vexcl.dat
	/usr/bin/time -f %e -o vexcl.dat -a ./vex_lorenz_ensemble $a > /dev/null
    done
    echo ""
done

kill $NVSMI_PID
